### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Zecozhang** [AndropaX/android_kernel_honor_hi6250#4]
Hello,I'm using this kernel source to compile a AospExtended for my Honor 9 Lite (LLD-AL10),and my device tree is https://github.com/CLickDev-Studio/android_device_honor_leland,when I trying to compile a bootimg,I get some wrong print.

 /home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/modem/taf/comm/src/acore/at/src/ATCmdProc.c:

 In function 'AT_HandleFacAuthPubKeyExCmd':
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/modem/taf/comm/src/acore/at/src/ATCmdProc.c:2803:5: error: implicit declaration of function 'AT_SetFacAuthPubkeyExPara' [-Werror=implicit-function-declaration]
     ulResult = AT_SetFacAuthPubkeyExPara(ucIndex, ulFirstParaVal, ulSecParaVal, usThirdParaLen, (pucData + usSecCommaPos));
     ^
  CC      drivers/leds/led-core.o
  CC      drivers/leds/led-class.o
  CC      drivers/hisi/tzdriver/agent.o
cc1: some warnings being treated as errors
/home/zeco/AEX/kernel/honor/hi6250/scripts/Makefile.build:274: recipe for target 'drivers/hisi/modem/taf/comm/src/acore/at/src/ATCmdProc.o' failed
make[5]: *** [drivers/hisi/modem/taf/comm/src/acore/at/src/ATCmdProc.o] Error 1
make[5]: *** 正在等待未完成的任务....
  CC      drivers/hisi/tzdriver/gp_ops.o
  CC      drivers/leds/led-triggers.o
  CC      drivers/leds/hisi_leds.o
/home/zeco/AEX/kernel/honor/hi6250/scripts/Makefile.build:435: recipe for target 'drivers/hisi/modem/taf' failed
make[4]: *** [drivers/hisi/modem/taf] Error 2
/home/zeco/AEX/kernel/honor/hi6250/scripts/Makefile.build:435: recipe for target 'drivers/hisi/modem' failed
make[3]: *** [drivers/hisi/modem] Error 2
make[3]: *** 正在等待未完成的任务....
  CC      drivers/leds/trigger/ledtrig-timer.o
  CC      drivers/hisi/tzdriver/mem.o
  LD      drivers/leds/trigger/built-in.o
  CC      drivers/hisi/tzdriver/tlogger.o
  CC      drivers/log_usertype/log-usertype2.o
  LD      drivers/leds/built-in.o
  CC      drivers/hisi/tzdriver/tee_rdr_register.o
  CC      drivers/hisi/tzdriver/agent_rpmb.o
/home/zeco/AEX/kernel/honor/hi6250/drivers/log_usertype/log-usertype2.c:69:5: warning: initialization from incompatible pointer type
     .write  = logusertype_write_proc2,
     ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/log_usertype/log-usertype2.c:69:5: warning: (near initialization for 'logusertype_proc_fops2.write')
  LD      drivers/log_usertype/built-in.o
  CC      drivers/hisi/tzdriver/libhwsecurec/memcpy_s.o
  CC      drivers/hisi/tzdriver/libhwsecurec/memset_s.o
  CC      drivers/md/dm-uevent.o
  CC      drivers/md/dm.o
  CC      drivers/hisi/tzdriver/libhwsecurec/strcpy_s.o
  CC      drivers/hisi/tzdriver/libhwsecurec/strncpy_s.o
  CC      drivers/md/dm-table.o
  CC      drivers/hisi/tzdriver/libhwsecurec/memmove_s.o
  CC      drivers/media/huawei/camera/hwcam_usrdev.o
  CC      drivers/hisi/tzdriver/libhwsecurec/strcat_s.o
  CC      drivers/hisi/tzdriver/libhwsecurec/strncat_s.o
  CC      drivers/hisi/tzdriver/libhwsecurec/strtok_s.o
  CC      drivers/hisi/tzdriver/libhwsecurec/securecutil.o
  CC      drivers/media/huawei/camera/hwcam_cfgdev.o
  CC      drivers/md/dm-target.o
  CC      drivers/hisi/tzdriver/libhwsecurec/secureprintoutput_a.o
  CC      drivers/hisi/tzdriver/libhwsecurec/snprintf_s.o
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/linux/pci.h:30:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/trace/events/iommu.h:14,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/iommu.h:27,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/../../drivers/staging/android/uapi/ion.h:22,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/ion.h:3,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/hisi/hisi_ion.h:19,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hwcam_cfgdev.c:7:
/home/zeco/AEX/kernel/honor/hi6250/include/linux/device.h:304:26: warning: 'driver_attr_hwcam_log' defined but not used [-Wunused-variable]
  struct driver_attribute driver_attr_##_name = __ATTR(_name, _mode, _show, _store)
                          ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hwcam_cfgdev.c:110:8: note: in expansion of macro 'DRIVER_ATTR'
 static DRIVER_ATTR(hwcam_log, 0664, hwcam_log_level_show, hwcam_log_level_store);
        ^
  CC      drivers/hisi/tzdriver/libhwsecurec/output.o
  CC      drivers/hisi/tzdriver/libhwsecurec/vsnprintf_s.o
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/tzdriver/libhwsecurec/output.c: In function 'securec_output_s':
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/tzdriver/libhwsecurec/output.c:824:1: warning: label 'FILL_STRING_BUFFER' defined but not used [-Wunused-label]
 FILL_STRING_BUFFER:
 ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/tzdriver/libhwsecurec/output.c:165:6: warning: unused variable 'bufferSize' [-Wunused-variable]
  int bufferSize = 0;               /* size of text.sz */
      ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/tzdriver/libhwsecurec/output.c: At top level:
/home/zeco/AEX/kernel/honor/hi6250/drivers/hisi/tzdriver/libhwsecurec/output.c:63:12: warning: 'indirectSprintf' defined but not used [-Wunused-function]
 static int indirectSprintf(char *strDest, const char *format, ...)
            ^
  CC      drivers/md/dm-linear.o
  CC      drivers/md/dm-stripe.o
  LD      drivers/hisi/tzdriver/libhwsecurec/built-in.o
  LD      drivers/hisi/tzdriver/built-in.o
/home/zeco/AEX/kernel/honor/hi6250/scripts/Makefile.build:435: recipe for target 'drivers/hisi' failed
make[2]: *** [drivers/hisi] Error 2
make[2]: *** 正在等待未完成的任务....
  CC      drivers/md/dm-ioctl.o
  CC      drivers/media/huawei/camera/hwcam_cfgpipeline.o
  CC      drivers/media/huawei/camera/hwcam_cfgstream.o
  CC      drivers/media/huawei/camera/hwcam_compat32.o
  CC      drivers/media/huawei/camera/cci/hw_cci.o
  CC      drivers/md/dm-io.o
  CC      drivers/media/huawei/camera/clt/hisi_clt_flag.o
  CC      drivers/md/dm-kcopyd.o
  LD      drivers/media/huawei/camera/clt/built-in.o
  CC      drivers/md/dm-sysfs.o
  LD      drivers/media/huawei/camera/cci/built-in.o
  CC      drivers/media/huawei/camera/csi/hw_csi.o
  CC      drivers/md/dm-stats.o
  CC      drivers/media/jpeg/jpeg_base.o
  CC      drivers/media/huawei/camera/hisp/hisp.o
  LD      drivers/media/jpeg/built-in.o
  CC      drivers/media/huawei/camera/hisp/hisp110/hisp110.o
  LD      drivers/media/huawei/camera/csi/built-in.o
  CC      drivers/media/huawei/camera/hjpeg/hjpgenc.o
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/linux/list.h:8:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/preempt.h:10,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/spinlock.h:50,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/seqlock.h:35,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/time.h:5,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/videodev2.h:59,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/media/huawei/hisp_cfg_base.h:8,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/media/huawei/hisp_cfg.h:7,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hisp/hisp.c:14:
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hisp/hisp.c: In function 'hisp_unregister':
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hisp/hisp.c:40:29: note: in expansion of macro 'container_of'
 #define  HwtoHisp(isp_intf) container_of(isp_intf, hisp_t, hw)
                             ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hisp/hisp.c:429:11: note: in expansion of macro 'HwtoHisp'
     isp = HwtoHisp(isp_intf);
           ^
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/asm-generic/gpio.h:4:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/gpio.h:51,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hjpeg/hjpgenc.c:27:
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hjpeg/hjpgenc.c: In function 'hjpeg_unregister':
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hjpeg/hjpgenc.c:56:28: note: in expansion of macro 'container_of'
 #define I2Hjpeg(jpeg_intf) container_of(jpeg_intf, hjpeg_t, intf)
                            ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/hjpeg/hjpgenc.c:280:13: note: in expansion of macro 'I2Hjpeg'
     jpeg =  I2Hjpeg(si);
             ^
  LD      drivers/media/huawei/camera/hjpeg/built-in.o
  CC      drivers/md/dm-builtin.o
  CC      drivers/md/dm-bufio.o
  CC      drivers/media/huawei/camera/io/hw_isp_io.o
  LD      drivers/media/huawei/camera/io/built-in.o
  CC      drivers/media/huawei/camera/laser/laser_common.o
  LD      drivers/media/huawei/camera/hisp/hisp110/built-in.o
  LD      drivers/media/huawei/camera/hisp/built-in.o
  CC      drivers/md/dm-bio-prison.o
  CC      drivers/md/dm-crypt.o
  LD      drivers/media/huawei/camera/laser/built-in.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor_common.o
  CC      drivers/media/huawei/camera/pmic/hw_pmic.o
  CC      drivers/media/huawei/camera/sensor/hwsensor.o
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/asm-generic/gpio.h:4:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/gpio.h:51,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c:5:
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c: In function 'hwsensor_unregister':
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c:426:27: note: in expansion of macro 'container_of'
 #define Intf2Hwsensor(si) container_of(si, hwsensor_t, intf)
                           ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c:430:26: note: in expansion of macro 'Intf2Hwsensor'
     hwsensor_t* sensor = Intf2Hwsensor(si);
                          ^
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: (near initialization for 'sensor')
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c:426:27: note: in expansion of macro 'container_of'
 #define Intf2Hwsensor(si) container_of(si, hwsensor_t, intf)
                           ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/hwsensor.c:430:26: note: in expansion of macro 'Intf2Hwsensor'
     hwsensor_t* sensor = Intf2Hwsensor(si);
                          ^
  CC      drivers/md/persistent-data/dm-array.o
  CC      drivers/media/huawei/camera/pmic/hw_pmic_i2c.o
  CC      drivers/media/huawei/camera/sensor/camerafs.o
  CC      drivers/media/huawei/camera/pmic/ncp6925.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx214.o
  CC      drivers/md/persistent-data/dm-bitset.o
  CC      drivers/media/huawei/camera/sensor/flash/hw_flash_i2c.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219.o
  LD      drivers/media/huawei/camera/pmic/built-in.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219BND.o
  CC      drivers/media/huawei/camera/sensor/flash/hw_flash.o
  CC      drivers/md/persistent-data/dm-block-manager.o
  CC      drivers/media/huawei/camera/sensor/flash/lm3642.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219FIG.o
  CC      drivers/md/persistent-data/dm-space-map-common.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov8856.o
  CC      drivers/md/persistent-data/dm-space-map-disk.o
  CC      drivers/media/huawei/camera/sensor/flash/mp3331.o
  CC      drivers/media/huawei/camera/sensor/flash/lm3642_front.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov8856BND.o
  CC      drivers/md/persistent-data/dm-space-map-metadata.o
  CC      drivers/md/persistent-data/dm-transaction-manager.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov8856FIG.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi843.o
  CC      drivers/media/huawei/camera/sensor/flash/mp3331_front.o
  CC      drivers/media/huawei/camera/sensor/flash/scharger_flash.o
  CC      drivers/md/persistent-data/dm-btree.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi843BND.o
  CC      drivers/md/persistent-data/dm-btree-remove.o
  LD      drivers/media/huawei/camera/sensor/flash/built-in.o
  CC      drivers/media/huawei/camera/sensor/ois/hwois.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi843FIG.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375BND.o
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/asm-generic/gpio.h:4:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/gpio.h:51,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c:27:
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c: In function 'hw_ois_unregister':
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c:230:24: note: in expansion of macro 'container_of'
 #define Intf2Hwois(si) container_of(si, hw_ois_t, intf)
                        ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c:234:21: note: in expansion of macro 'Intf2Hwois'
  hw_ois_t* hw_ois = Intf2Hwois(intf);
                     ^
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: (near initialization for 'hw_ois')
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c:230:24: note: in expansion of macro 'container_of'
 #define Intf2Hwois(si) container_of(si, hw_ois_t, intf)
                        ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/ois/hwois.c:234:21: note: in expansion of macro 'Intf2Hwois'
  hw_ois_t* hw_ois = Intf2Hwois(intf);
                     ^
  CC      drivers/md/persistent-data/dm-btree-spine.o
  CC      drivers/media/huawei/camera/sensor/ois/lc8981.o
  CC      drivers/media/huawei/camera/sensor/vcm/hwvcm.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375FIG.o
  LD      drivers/media/huawei/camera/sensor/ois/built-in.o
  CC      drivers/media/huawei/camera/sensor/vcm/dw9714.o
  LD      drivers/md/persistent-data/dm-persistent-data.o
  LD      drivers/md/persistent-data/built-in.o
  CC      drivers/md/dm-verity-fec.o
In file included from /home/zeco/AEX/kernel/honor/hi6250/include/asm-generic/gpio.h:4:0,
                 from /home/zeco/AEX/kernel/honor/hi6250/include/linux/gpio.h:51,
                 from /home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c:27:
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c: In function 'hw_vcm_unregister':
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c:234:24: note: in expansion of macro 'container_of'
 #define Intf2Hwvcm(si) container_of(si, hw_vcm_t, intf)
                        ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c:238:21: note: in expansion of macro 'Intf2Hwvcm'
  hw_vcm_t* hw_vcm = Intf2Hwvcm(intf);
                     ^
/home/zeco/AEX/kernel/honor/hi6250/include/linux/kernel.h:817:48: warning: (near initialization for 'hw_vcm')
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c:234:24: note: in expansion of macro 'container_of'
 #define Intf2Hwvcm(si) container_of(si, hw_vcm_t, intf)
                        ^
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/huawei/camera/sensor/vcm/hwvcm.c:238:21: note: in expansion of macro 'Intf2Hwvcm'
  hw_vcm_t* hw_vcm = Intf2Hwvcm(intf);
                     ^
  CC      drivers/md/dm-verity-target.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375RNE.o
  CC      drivers/media/huawei/camera/sensor/vcm/ad5816.o
  CC      drivers/media/huawei/camera/sensor/vcm/ad5823.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375RNEFRONT.o
  CC      drivers/md/dm-cache-target.o
  LD      drivers/media/huawei/camera/sensor/vcm/built-in.o
  LD      drivers/media/huawei/camera/sensor/built-in.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259BND.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259FIG.o
  CC      drivers/media/v4l2-core/v4l2-dev.o
  CC      drivers/media/v4l2-core/v4l2-ioctl.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259RNE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259RNEFRONT.o
  CC      drivers/media/v4l2-core/v4l2-device.o
  CC      drivers/md/dm-cache-metadata.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx386E3.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov12870E3.o
  CC      drivers/media/v4l2-core/v4l2-fh.o
  CC      drivers/md/dm-cache-policy.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov12a10.o
  CC      drivers/md/dm-cache-policy-cleaner.o
  CC      drivers/media/v4l2-core/v4l2-event.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov12a10PIC.o
  CC      drivers/media/v4l2-core/v4l2-ctrls.o
  LD      drivers/md/dm-mod.o
  LD      drivers/md/dm-verity.o
  LD      drivers/md/dm-cache.o
  LD      drivers/md/dm-cache-cleaner.o
  LD      drivers/md/built-in.o
  CC      drivers/media/v4l2-core/v4l2-subdev.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov12a10hybird.o
  CC      drivers/media/v4l2-core/v4l2-clk.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx486.o
  CC      drivers/media/v4l2-core/v4l2-async.o
  CC      drivers/media/media-device.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx486PIC.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov20880.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov20880BAC.o
  CC      drivers/media/v4l2-core/v4l2-compat-ioctl32.o
  CC      drivers/media/v4l2-core/v4l2-of.o
/home/zeco/AEX/kernel/honor/hi6250/drivers/media/v4l2-core/v4l2-compat-ioctl32.c:48:12: warning: 'get_v4l2_window32' defined but not used [-Wunused-function]
 static int get_v4l2_window32(struct v4l2_window *kp, struct v4l2_window32 __user *up)
            ^
  CC      drivers/media/v4l2-core/vb2-trace.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx376.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx376BAC.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx486hybird.o
  CC      drivers/media/v4l2-core/v4l2-trace.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov8858.o
  CC      drivers/media/media-devnode.o
  CC      drivers/media/media-entity.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219HDN.o
  CC      drivers/media/v4l2-core/v4l2-common.o
  CC      drivers/media/v4l2-core/v4l2-dv-timings.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219HDN_BACK.o
  LD      drivers/media/media.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov16b10BND.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov16b10RNE.o
  CC      drivers/media/v4l2-core/videobuf2-core.o
  CC      drivers/media/v4l2-core/videobuf2-v4l2.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx298.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx298RNE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx498RNE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx498.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov13855RNE.o
  LD      drivers/media/v4l2-core/videodev.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx258FIG.o
  LD      drivers/media/v4l2-core/built-in.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi1333FIG.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi1333RNE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov13855FIG.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov13855LLD.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi1333LLD.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx258LLD.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259LLD.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375LLD.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov13855LLDFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi1333LLDFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx258LLDFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259LLDFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375LLDFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov13855FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi1333FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx258FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi843FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx219FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov8856FLA.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/s5k3p8FLAFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx371FLAFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov16885FLAFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259FLAFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375FLAFRONT.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/gc2375ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/hi259ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov16b10ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx498ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/s5k3p8ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx371ANE.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx576.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/ov16885.o
  CC      drivers/media/huawei/camera/platform/hi6250/sensor/imx319.o
  LD      drivers/media/huawei/camera/platform/hi6250/sensor/built-in.o
  LD      drivers/media/huawei/camera/platform/hi6250/built-in.o
  LD      drivers/media/huawei/camera/platform/built-in.o
  LD      drivers/media/huawei/camera/built-in.o
  LD      drivers/media/huawei/built-in.o
  LD      drivers/media/built-in.o
/home/zeco/AEX/kernel/honor/hi6250/Makefile:1035: recipe for target 'drivers' failed
make[1]: *** [drivers] Error 2
make[1]: 离开目录“/home/zeco/AEX/out/target/product/leland/obj/KERNEL_OBJ”
Makefile:152: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
make: Leaving directory '/home/zeco/AEX/kernel/honor/hi6250'
ninja: build stopped: subcommand failed.
11:58:34 ninja failed with: exit status 1

#### failed to build some targets (06:44 (mm:ss)) ####

zeco@zeco-Workstation:~/AEX$ 

P.S. I cannot flash your ROM post on XDA,too.If it caused by my phone is a China Market model?

**Comment by AndropaX** [comment]
It's Huawei source issue, I don't care about Kernel, because it's not necessary to touch it...

**Comment by Zecozhang** [comment]
But why cannot I flash your ROM？
